# Generated by Django 6.0.1 on 2026-01-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lesson'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
    ]
